### ISSUE TITLE
PyBDSF

### ISSUE THREAD

**Issue by EFOcran** [idia-astro/idia-container-sourcefinding#2]
The latest version of the code and installations instructions are available on the PyBDSF GitHub page at https://github.com/lofar-astron/PyBDSF.

**Comment by Shadowphax** [comment]
Hi, 

We have redeployed the container based on a number of improvements within the build definition file. There are currently two source finding containers. The most recent one is " sourcefinding.img" which is a symbolic link to the "sourcefinding-.img". Please test and update this issue. 

Please no longer use the "source-finding.img" container.

**Comment by daikema** [comment]
So taking a peak at this, I don't see a `pybdsf` binary but there is a `pybsdm` one now (which I don't think was there before.  @EFOcran does the pybdsf binary work for you?

**Comment by Shadowphax** [comment]
Have not received any feedback related to this issue. Please reopen if still broken.

**Comment by EFOcran** [comment]
pybdsf doesn't work but pybdsm works fine.

**Comment by Shadowphax** [comment]
Hi,


I have added pybdsf to the container. Can you test and confirm ?


Regards

Timothy



[1453983687829_image002.png]
Timothy Carr - /\/¯¯¯¯¯\/\
Senior Technical Specialist
Tel: +27 21 650 3014
Cell: +27 83 457 2568

________________________________
