### ISSUE TITLE
Add docopt and mpld3

### ISSUE THREAD

**Issue by Jordatious** [idia-astro/idia-container-sourcefinding#4]
Could we please get docopt (for python 2.7) added to this container?

**Comment by Jordatious** [comment]
Could we please also get mpld3 added?

**Comment by Shadowphax** [comment]
Added docopt and mpld3 to the sourcefinding.img container - [fdc354f](https://github.com/idia-astro/idia-container-sourcefinding/commit/fdc354fcdbfb2fbb238e72b8a5953ea7686f9482)
