### ISSUE TITLE
WCS error

### ISSUE THREAD

**Issue by Jordatious** [idia-astro/idia-container-sourcefinding#5]
When I run the following code (where my_image is just a string with the filepath) I get this error for the 4th last line. Am I doing something wrong? The following import statements work fine.

Import statements:

    from astropy.io import fits
    from astropy.wcs import WCS
    import matplotlib.pyplot as plt

Code:

    #HDU axis 0 is the image data
    img = fits.open(my_image)[0]

    #Image header with NAXES starting from 1
    head = img.header

    #WCS object with naxis starting from 0
    w = WCS(head)

    fig=plt.figure(**figsize)
    ax = fig.add_subplot(111, projection=w)
    plt.xlabel('RA')
    plt.ylabel('Dec')
    plt.imshow(img.data[0][0], origin='lower',vmin=-0.002,vmax=0.002,cmap=plt.cm.viridis)

Error:

    ImportError: Using WCS instances as Matplotlib projections requires the WCSAxes package to be installed. See http://wcsaxes.readthedocs.org for more details.

**Comment by Shadowphax** [comment]
Installed WCSAxes - " pip install WCSAxes " Committed to [7a90f53](https://github.com/idia-astro/idia-container-sourcefinding/commit/7a90f5361771f44f072bad43311489ee07761f69)
